In [1]:
from sklearn import datasets 
import numpy as np

In [2]:
iris = datasets.load_iris()
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [3]:
X = iris.data
y = iris.target

In [4]:
X.shape

(150, 4)

In [5]:
y.shape

(150,)

In [6]:
shuffled_indexes = np.random.permutation(len(X))

In [7]:
shuffled_indexes

array([ 86,  42,  71,  14, 148,   8, 125,  29,  98,  10,  13, 107,  19,
       146, 147,  12, 139,  57,  84, 131,  88, 122,  65,  17,   1, 108,
        40,  63,  68, 128,  24,  52, 119,  79,  69, 129,  91, 121, 110,
       109, 141, 132, 149,  74,  77,  18,  78,  87,  90,  50,   2, 106,
        35, 118, 114,  16,  41,  25,  55, 130,  21,   6,  11, 100, 112,
        47, 135,  73, 133,  23,  39, 115,  45,  56,  93,  26,  36,  82,
       113,  32,  28, 103,  31,  51, 137, 144,  46,  27, 136, 138, 124,
         0,  38,  70,  83,  85,  66,  30,  75, 104,  54, 120,  92,   3,
        43,   4,  33,  99,  67,  15,  94, 140,  95,  53,  58,  20, 105,
        97,  72,  61,  48, 116, 123, 102, 143,  22,  44, 117, 101,  80,
       134,  34,  81,  37,  89, 142,  59,  96,  76, 127,  64, 126,  60,
         7,  62, 111,  49, 145,   9,   5])

In [8]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [9]:
test_indexes = shuffled_indexes[:test_size]
train_indexes = shuffled_indexes[test_size:]
X_test = X[test_indexes]
y_test = y[test_indexes]
X_train = X[train_indexes]
y_train = y[train_indexes]

In [10]:
X_test.shape

(30, 4)

In [11]:
X_train.shape

(120, 4)

In [12]:
y_test.shape

(30,)

## 封装自定义 train_test_split

In [18]:
import sys
sys.path.append('/home/zhuf/CodingSpace/DataScience_Learning/machine_learning')

In [19]:
from playML.model_selection import  train_test_split
from playML.KNN import KNN_classifier

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [21]:
my_knn_clf = KNN_classifier(2)
my_knn_clf.fit(X_train, y_train)
y_predit = my_knn_clf.predict(X_test)

In [22]:
y_predit

array([1, 1, 0, 2, 2, 1, 1, 2, 0, 2, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 2, 1,
       2, 1, 2, 0, 2, 1, 2, 0])

In [23]:
y_test

array([1, 1, 0, 2, 2, 1, 1, 2, 0, 2, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 2, 1,
       2, 1, 2, 0, 1, 1, 2, 0])

In [24]:
print(sum(y_predit == y_test))
print(np.sum(y_predit == y_test))

29
29


## 封装自定义accuracy_score,KNN类自定义score方法

In [25]:
from playML.metrics import accuracy_score

In [26]:
accuracy_score(y_test, y_predit)

0.9666666666666667

In [27]:
my_knn_clf.score(X_test, y_test)

0.9666666666666667

## 使用sklearn中的train_test_split

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [30]:
X_train.shape

(120, 4)

In [31]:
X_test.shape

(30, 4)

In [32]:
%timeit sum(y_predit == y_test)

53.4 µs ± 2.9 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [33]:
%timeit np.sum(y_predit == y_test)

5.11 µs ± 337 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [34]:
np.sum(y_predit == y_test)

10