In [1]:
from sklearn import datasets 
import numpy as np

In [2]:
iris = datasets.load_iris()
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [3]:
X = iris.data
y = iris.target

In [4]:
X.shape

(150, 4)

In [5]:
y.shape

(150,)

In [6]:
shuffled_indexes = np.random.permutation(len(X))

In [7]:
shuffled_indexes

array([ 34,  92,  40, 123, 147,  17,  23,  37,  53, 139, 105,  15,  89,
       115,  44,  70,  36,  55,  69,  86,  85, 113, 126,  61,  24,  87,
        14, 129,  21,  38,   6,  48,  74,  16,  54,   0,  94, 116,  35,
        62, 111, 108,  28, 140, 119,  76, 133,  67,  95, 135, 101,  75,
        52,  71,  32,   7, 102,  25, 109,  79,  43,  10,  30,   3,   5,
       149,   1, 141,  22, 148,   4,  63, 107,  20, 142,  60,  41,  88,
        64, 110,  27, 106, 145,  42, 125, 120,  47,  80,  66, 122, 127,
        46, 146,  81,  68,  59,  39,  78,  31, 144,  90, 121, 130, 103,
       132, 114,  18,  73,  82,  97, 143,  58,  96,  50,  91,  11,   9,
        65,  26,  83, 134,  57,  45,  19,   8,  33,  29,  72,  51, 138,
        84, 136, 118, 117, 100,   2,  99,  12,  77, 124, 112, 104, 128,
       131,  93,  49,  98,  13, 137,  56])

In [8]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [9]:
test_indexes = shuffled_indexes[:test_size]
train_indexes = shuffled_indexes[test_size:]
X_test = X[test_indexes]
y_test = y[test_indexes]
X_train = X[train_indexes]
y_train = y[train_indexes]

In [10]:
X_test.shape

(30, 4)

In [11]:
X_train.shape

(120, 4)

In [12]:
y_test.shape

(30,)

## 封装自定义 train_test_split

In [13]:
from playML.model_selection import  train_test_split
from playML.KNN import KNN_classifier

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [15]:
my_knn_clf = KNN_classifier(2)
my_knn_clf.fit(X_train, y_train)
y_predit = my_knn_clf.predict(X_test)

In [16]:
y_predit

array([0, 1, 1, 1, 0, 1, 2, 0, 1, 0, 2, 2, 1, 1, 1, 1, 0, 2, 2, 0, 1, 0,
       2, 0, 2, 2, 0, 2, 0, 2])

In [17]:
y_test

array([0, 1, 1, 1, 0, 2, 2, 0, 1, 0, 2, 2, 1, 1, 1, 1, 0, 2, 2, 0, 1, 0,
       2, 0, 2, 2, 0, 2, 0, 2])

In [18]:
print(sum(y_predit == y_test))
print(np.sum(y_predit == y_test))

29
29


## 封装自定义accuracy_score,KNN类自定义score方法

In [19]:
from playML.metrics import accuracy_score

In [20]:
accuracy_score(y_test, y_predit)

0.9666666666666667

In [21]:
my_knn_clf.score(X_test, y_test)

0.9666666666666667

## 使用sklearn中的train_test_split

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [24]:
X_train.shape

(120, 4)

In [25]:
X_test.shape

(30, 4)

In [26]:
%timeit sum(y_predit == y_test)

113 µs ± 7.37 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [27]:
%timeit np.sum(y_predit == y_test)

8.01 µs ± 99.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [28]:
np.sum(y_predit == y_test)

14