In [1]:
import numpy as np
print(np.__version__)

1.17.2


## 遍历

In [2]:
b = np.arange(6).reshape(3,2)
for i in b:    # 对于二维数组，相当与遍历行
    print(i)

[0 1]
[2 3]
[4 5]


In [3]:
for i in b.flat:
    print(i)

0
1
2
3
4
5


## 索引、切片

In [4]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 取单个元素

In [5]:
# 获取单独一个值的时候，可以使用 a[(2,3)]，X[2][3]但是不建议
a[2,3]

13

In [6]:
a[2][3]

13

In [7]:
# 使用两个中括号会引起歧义，获得不是想要的结果
a[2:,:2]

array([[10, 11]])

In [8]:
a[2:][:2]

array([[10, 11, 12, 13, 14]])

In [9]:
a[1:, 3]

array([ 8, 13])

In [10]:
a[0:3:2, 0:5:2]

array([[ 0,  2,  4],
       [10, 12, 14]])

In [11]:
a[[0,2],[3,4]]

array([ 3, 14])

# 视图和拷贝问题

In [12]:
a = np.arange(6).reshape(2,3)
b = a
c = a.view()
d = a.copy()
a

array([[0, 1, 2],
       [3, 4, 5]])

In [13]:
id(a)

2199559403040

In [14]:
id(b)

2199559403040

In [15]:
id(c)

2199559251328

In [16]:
id(d)

2199559250688

In [17]:
a[0] = 9999
a

array([[9999, 9999, 9999],
       [   3,    4,    5]])

In [18]:
b

array([[9999, 9999, 9999],
       [   3,    4,    5]])

In [19]:
c

array([[9999, 9999, 9999],
       [   3,    4,    5]])

In [20]:
d

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
a.resize(3,2)
a

array([[9999, 9999],
       [9999,    3],
       [   4,    5]])

In [22]:
# b和a完全相同
b

array([[9999, 9999],
       [9999,    3],
       [   4,    5]])

In [23]:
# c和a指向相同的实际数据部分
# 实际数据部分相同表示数据部分在内存中的存储形式是一样的
# 但是数据在numpy数组中的表现形式是不一样的
# 也就说一个内存形式的数据可以映射为不同的numpy数组表现形式，与之对应的操作也相应发生变化
c

array([[9999, 9999, 9999],
       [   3,    4,    5]])

In [24]:
d

array([[0, 1, 2],
       [3, 4, 5]])

### 注意numpy的切片是以类似引用的方式进行的，这与python的list有所不同

In [25]:
l = [i for i in range(9)]
l

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [26]:
subl= l[2:6]
subl

[2, 3, 4, 5]

In [27]:
subl[0] = 999

In [28]:
subl

[999, 3, 4, 5]

In [29]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [30]:
X = np.arange(12).reshape(4,3)
X

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [31]:
subX = X[:2,:2]

In [32]:
subX

array([[0, 1],
       [3, 4]])

In [33]:
subX[1,1] = 999

In [34]:
subX

array([[  0,   1],
       [  3, 999]])

In [35]:
X

array([[  0,   1,   2],
       [  3, 999,   5],
       [  6,   7,   8],
       [  9,  10,  11]])

In [36]:
# 如果想让切片不以引用的方式进行，可需要copy方法
X[1,1] = 4
X

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [37]:
subX2 = X[:2,:2].copy()
subX2

array([[0, 1],
       [3, 4]])

In [38]:
subX2[1,1] = 999

In [39]:
subX2

array([[  0,   1],
       [  3, 999]])

In [40]:
X

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [41]:
X[:2,]

array([[0, 1, 2],
       [3, 4, 5]])

In [42]:
X

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [43]:
X[:,:2]

array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10]])