In [1]:
import numpy as np
print(np.__version__)

1.18.1


## 遍历

In [2]:
b = np.arange(6).reshape(3,2)
for i in b:    # 对于二维数组，相当与遍历行
    print(i)

[0 1]
[2 3]
[4 5]


In [3]:
for i in b.flat:
    print(i)

0
1
2
3
4
5


## 索引、切片

In [4]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 取单个元素

In [5]:
# 获取单独一个值的时候，可以使用 a[(2,3)]，X[2][3]但是不建议
a[2,3]

13

In [6]:
a[2][3]

13

In [7]:
# 使用两个中括号会引起歧义，获得不是想要的结果
a[2:,:2]

array([[10, 11]])

In [8]:
a[2:][:2]

array([[10, 11, 12, 13, 14]])

In [9]:
a[1:, 3]

array([ 8, 13])

In [10]:
a[0:3:2, 0:5:2]

array([[ 0,  2,  4],
       [10, 12, 14]])

In [11]:
a[[0,2],[3,4]]

array([ 3, 14])

# 视图和拷贝问题

In [12]:
a = np.arange(6).reshape(2,3)
b = a
c = a.view()
d = a.copy()
a

array([[0, 1, 2],
       [3, 4, 5]])

In [13]:
id(a)

140085776238032

In [14]:
id(b)

140085776238032

In [15]:
id(c)

140085776085680

In [16]:
id(d)

140085776085440

In [17]:
a[0] = 9999
a

array([[9999, 9999, 9999],
       [   3,    4,    5]])

In [18]:
b

array([[9999, 9999, 9999],
       [   3,    4,    5]])

In [19]:
c

array([[9999, 9999, 9999],
       [   3,    4,    5]])

In [20]:
d

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
a.resize(3,2)
a

array([[9999, 9999],
       [9999,    3],
       [   4,    5]])

In [22]:
# b和a完全相同
b

array([[9999, 9999],
       [9999,    3],
       [   4,    5]])

In [23]:
# c和a指向相同的实际数据部分
# 实际数据部分相同表示数据部分在内存中的存储形式是一样的
# 但是数据在numpy数组中的表现形式是不一样的
# 也就说一个内存形式的数据可以映射为不同的numpy数组表现形式，与之对应的操作也相应发生变化
c

array([[9999, 9999, 9999],
       [   3,    4,    5]])

In [24]:
d

array([[0, 1, 2],
       [3, 4, 5]])

In [25]:
l = [i for i in range(9)]
l

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [26]:
subl= l[2:6]
subl

[2, 3, 4, 5]

In [27]:
subl[0] = 999

In [28]:
subl

[999, 3, 4, 5]

In [29]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [30]:
X = np.arange(12).reshape(4,3)
X

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [31]:
subX = X[:2,:2]

In [32]:
subX

array([[0, 1],
       [3, 4]])

In [33]:
subX[1,1] = 999

In [34]:
subX

array([[  0,   1],
       [  3, 999]])

In [35]:
X

array([[  0,   1,   2],
       [  3, 999,   5],
       [  6,   7,   8],
       [  9,  10,  11]])

In [36]:
# 如果想让切片不以引用的方式进行，可需要copy方法
X[1,1] = 4
X

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [37]:
subX2 = X[:2,:2].copy()
subX2

array([[0, 1],
       [3, 4]])

In [38]:
subX2[1,1] = 999

In [39]:
subX2

array([[  0,   1],
       [  3, 999]])

In [40]:
X

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [41]:
X[:2,]

array([[0, 1, 2],
       [3, 4, 5]])

In [42]:
X

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [43]:
X[:,:2]

array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10]])

In [44]:
y = np.arange(35).reshape(5,7)

## Fancy Indexing

In [45]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [47]:
# 切片语法不能在fancy indexing的数组表示中再使用
#y[[0,1,4],[0:3]]

SyntaxError: invalid syntax (<ipython-input-47-b77c2b4e3661>, line 1)

In [49]:
y[[0,2,4], [0,1,2]]

array([ 0, 15, 30])

In [53]:
y[[0,2,4], 1]

array([ 1, 15, 29])

In [54]:
y[[0,2,4],[1,2]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [55]:
y[[0,2,4]]

array([[ 0,  1,  2,  3,  4,  5,  6],
       [14, 15, 16, 17, 18, 19, 20],
       [28, 29, 30, 31, 32, 33, 34]])

In [56]:
a = np.arange(12)**2

In [57]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [58]:
a[[ 1,1,3,8,5 ]]

array([ 1,  1,  9, 64, 25])

In [65]:
j = np.array([[ 3, 4], [ 9, 7 ]])

In [66]:
a[j]

array([[ 9, 16],
       [81, 49]])

In [67]:
i = [ [ 3, 4], [ 9, 7 ] ]

In [69]:
# 不能使用python二维列表作为索引数组，最好使用numpy的二维数组
# a[i]

## 取指定行列的子矩阵

In [72]:
a = np.arange(30).reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [73]:
# 使用数组索引的方式得到的结果并不是想要的
a[[1,2,4], [1,2,5]]

array([ 7, 14, 29])

In [ ]:
使用索引数组并不能截取想要的子数组，需要另一种方法ix_

In [75]:
row = [1, 2, 4]
col = [1, 2, 5]
a[np.ix_(row, col)]

array([[ 7,  8, 11],
       [13, 14, 17],
       [25, 26, 29]])

In [77]:
a[[1,2,4]] [:, [1,2,5]]

array([[ 7,  8, 11],
       [13, 14, 17],
       [25, 26, 29]])

In [78]:
a[[1,2,4]]

array([[ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [24, 25, 26, 27, 28, 29]])