In [1]:
import numpy as np
np.__version__

'1.17.2'

# 关于数据的维度
* 数据组织的维度和数据属性的维度似乎不一样
* 数据组织的维度是以一维数组、二维数组、多维数组等形式来表示
* 数据属性的维度是一个数据对象具有多少个属性

注意数组的维度

一维数组是线型的，一边只有一个中括号

二维数组的面型的，一边有两个中括号

三维数组是体型的，一边有三个中括号

数组形状信息由shape属性表示，注意shape是一个元组，对于一维数组，它只有一个元素, 二维数组的shape有两个元素，先行后列

数组的维度信息由ndim属性表示，相当于len(shape)

数组元素的个数由size属性表示


In [2]:
l = [2,4,5,6,8]
a = np.array(l)
print('array:', a)
print('shape:', a.shape)
print('ndim:', a.ndim)
print('size:', a.size)

array: [2 4 5 6 8]
shape: (5,)
ndim: 1
size: 5


In [3]:
a = a.reshape(1,5)
print('array:', a)
print('shape:', a.shape)
print('ndim:', a.ndim)
print('size:', a.size)

array: [[2 4 5 6 8]]
shape: (1, 5)
ndim: 2
size: 5


In [4]:
a = a.reshape(5,1)
print('array:')
print(a)
print('shape:', a.shape)
print('ndim:', a.ndim)
print('size:', a.size)

array:
[[2]
 [4]
 [5]
 [6]
 [8]]
shape: (5, 1)
ndim: 2
size: 5


In [5]:
a = np.arange(12).reshape(3,4)
print('array:')
print(a)
print('shape:', a.shape)
print('ndim:', a.ndim)
print('size:', a.size)

array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
shape: (3, 4)
ndim: 2
size: 12


# 基本运算操作

In [6]:
# + - × ÷ 
a = np.arange(4).reshape(2,2)
b = np.array([[4,3],[2,1]])

In [7]:
a

array([[0, 1],
       [2, 3]])

In [8]:
b

array([[4, 3],
       [2, 1]])

In [9]:
a + b

array([[4, 4],
       [4, 4]])

In [10]:
a * b 

array([[0, 3],
       [4, 3]])

In [11]:
# 矩阵乘法 使用@符号，但要求Python版本3.5以上，或者使用dot方法
a @ b

array([[ 2,  1],
       [14,  9]])

In [12]:
a.dot(b)

array([[ 2,  1],
       [14,  9]])

In [13]:
np.dot(a,b)

array([[ 2,  1],
       [14,  9]])

In [14]:
# +=、-=、*=、/=诸如这些符号表示在左边操作对象上就地修改,但还不支持@=这种操作，可以使用a = a @ b
a+=b

In [15]:
a

array([[4, 4],
       [4, 4]])

In [16]:
b

array([[4, 3],
       [2, 1]])

In [17]:
a*=b

In [18]:
a

array([[16, 12],
       [ 8,  4]])

In [19]:
a/=b

TypeError: No loop matching the specified signature and casting was found for ufunc true_divide

## 关于轴的问题

In [20]:
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [21]:
a.sum(axis=1)

array([1, 5, 9])

In [22]:
a.sum(axis=0)

array([6, 9])

In [23]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [24]:
a.sum(axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [25]:
a.sum(axis=1)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [26]:
a.sum(axis=2)

array([[ 6, 22, 38],
       [54, 70, 86]])

# 通用函数

In [ ]:
a = np.arange(8)
a

In [ ]:
np.diff(a)

In [ ]:
a = np.random.randint(0,100,(3,4))
a

In [ ]:
np.diff(a)

In [ ]:
# np.maximum和np.max的区别
# 前者是基于元素较两个数组，返回一个数组
# 后者是全局比较

# 布尔运算

## 等于

In [ ]:
a = np.arange(5)
b = (a==2)
c = a[b]
a

In [ ]:
b

In [ ]:
c

In [ ]:
a = np.array([[2,4,5,4],[9,4,1,4]])
b = (a==4)
c = a[b]
a

In [ ]:
b

In [ ]:
c

In [ ]:
# where函数
a = np.arange(5)
b = np.array([4,3,2,4,9])
cond = np.array([True,False,False,True,True])
print(a)
print(b)
# True取ａ，False取ｂ
np.where(cond,a,b)

## 与或非 & | 

# 随机函数