## 拼接和分割

In [34]:
# concatenate
a = np.arange(5)
b = np.zeros(5)
# np.concatenate(a,b) # 错
np.concatenate((a,b))

array([0., 1., 2., 3., 4., 0., 0., 0., 0., 0.])

### 拼接

### 分割

In [35]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

平均分割，有一个标量数字表示

In [36]:
np.hsplit(a,3)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

指定分割，用元组(a,b)表示在序号为a、b上分别切一刀

In [37]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [38]:
np.hsplit(a, (1,3))

[array([[ 0],
        [ 5],
        [10]]), array([[ 1,  2],
        [ 6,  7],
        [11, 12]]), array([[ 3,  4],
        [ 8,  9],
        [13, 14]])]