In [1]:
import numpy as np

## 数据类型

### 数据类型转换

In [55]:
# ndarray.astype方法一定会创建一个新的数组，即使两个数组类型一样
a = np.arange(24)
b = a.astype(np.float)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [56]:
b

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

In [57]:
# 还可以直接使用Numy内置的类型名称进行类型转换
a = np.arange(10)
b = np.float32(a)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [59]:
# ! 注意np.float表示python内置浮点类型，不能用于numpy数组类型的转换，可以使用np.float32或者np.float64
b = np.float(a)   

TypeError: only size-1 arrays can be converted to Python scalars

In [ ]:
a = np.full((4,3), 1.0)
a

In [ ]:
b = np.int8(a)
b

### 创建自定义数据类型

In [ ]:
t = np.dtype([('name', np.str_, 40), ('num_items', np.int), ('price', np.float)])
t