In [1]:
import numpy as np
np.__version__

'1.17.2'

## 创建数组

### 从列表和元组中创建

In [2]:
np.array([2,3,4])

array([2, 3, 4])

### 使用numpy内置函数

In [3]:
# np.ones(shape)   np.ones_like(a)
# np.zeros(shape)    np.zeros_like(a)
# np.full(shape, val)    np.full_like(shape, val)
# np.eye(n)  单位矩阵
# np.empty(shape) 未被初始化
# np.arange(start=0, end, step=1)
# np.linspace(start, stop, n_points=50)

In [5]:
# python中的range和numpy的arange的异同
# python的range只能接受整数作为参赛，np.arange可以接受浮点数

In [7]:
np.linspace?

Signature:
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Docstring:
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is False.
num : int, optional
    Number of samples to generate. Default is 50. Must be non-negative.
endpoint : bool, optional
    If True, `stop` is the last sample. Otherwise, it is not included.
    Default is True.
retstep : 

In [6]:
# linspace 指定起始点和元素个数
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [29]:
# 默认包括终点，设置endpoint=False可以不包括终点
np.linspace(0,10,4, endpoint=False)

array([0. , 2.5, 5. , 7.5])

In [30]:
# 默认创建50个点
a = np.linspace(0,10)
print(a.size)
a

50


array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [31]:
a = np.array([4,5,3,2], dtype=np.float)
a.dtype

dtype('float64')

In [32]:
np.float32([4,3,2])  # 但是np.float不行

array([4., 3., 2.], dtype=float32)

# 文本文件
___

* loadtxt(fname[, dtype,comments,delimiter, …]) 从文本文件导入数据
* savetxt(fname,X[, fmt, delimiter, newline, …]) 将一个数组保存到文本文件
* genfromtxt(fname[, dtype, comments, …]) 从文本文件中导入数据，同时处理指定的缺失值
* ndarray.tofile(fid[, sep, format]) 将数组写入到文本或二进制（默认)文件

# Numpy二进制文件
___

* load(file, mmap_mode, allow_pickle, …])  从.npy, .npz或pickled文件中载入（多个）数组
* save(file, arr[, allow_pickle, fix_imports])  将一个数组保存为Numpy .npy格式的二进制文件
* savez(file, *args, **kwds) 将多个数组保存到单独一个未压缩的.npz格式的文件中
* savez_compressed(file, *args, **kwds) 将多个数组保存到单独一个压缩了的.npz格式的文件中

##   Numpy二进制格式.npy .npz
___

* .npy是numpy序列化_单一数组_的标准二进制格式，.npy只能保存一个数组
* .npz是numpy序列化_多个数组_的标准二进制格式，一个.npz文件是多个.npy文件的zip包，其中一个.npy文件对应一个数组

# 原始二进制文件
___

* fromfile(file[, dtype, count, sep])  从一个二进制或文本文件中创建一个数组
* ndarray.tofile(fid[, sep, format])   将（一个）数组以二进制（默认）或者文本格式写到文件中

In [33]:
a =  np.eye(5)
np.savetxt('eye.txt', a)