In [1]:
import numpy as np
np.__version__

'1.16.2'

# 关于数据的维度
* 数据组织的维度和数据属性的维度似乎不一样
* 数据组织的维度是以一维数组、二维数组、多维数组等形式来表示
* 数据属性的维度是一个数据对象具有多少个属性

注意数组的维度

一维数组是线型的，一边只有一个中括号
二维数组的面型的，一边有两个中括号
三维数组是体型的，一边有三个中括号

数组形状信息由shape属性表示，注意shape是一个元组，对于一维数组，它只有一个元素, 二维数组的shape有两个元素，先行后列

数组的维度信息由ndim属性表示，相当于len(shape)
数组元素的个数由size属性表示


In [2]:
l = [2,4,5,6,8]
a = np.array(l)
print('array:', a)
print('shape:', a.shape)
print('ndim:', a.ndim)
print('size:', a.size)

array: [2 4 5 6 8]
shape: (5,)
ndim: 1
size: 5


In [3]:
a = a.reshape(1,5)
print('array:', a)
print('shape:', a.shape)
print('ndim:', a.ndim)
print('size:', a.size)

array: [[2 4 5 6 8]]
shape: (1, 5)
ndim: 2
size: 5


In [4]:
a = a.reshape(5,1)
print('array:')
print(a)
print('shape:', a.shape)
print('ndim:', a.ndim)
print('size:', a.size)

array:
[[2]
 [4]
 [5]
 [6]
 [8]]
shape: (5, 1)
ndim: 2
size: 5


# 基本运算操作

In [7]:
# + - × ÷ 
a = np.arange(4).reshape(2,2)
b = np.array([[4,3],[2,1]])

In [8]:
a

array([[0, 1],
       [2, 3]])

In [9]:
b

array([[4, 3],
       [2, 1]])

In [10]:
a + b

array([[4, 4],
       [4, 4]])

In [11]:
a * b 

array([[0, 3],
       [4, 3]])

In [12]:
# 矩阵乘法 使用@符号，但要求Python版本3.5以上，或者使用dot方法
a @ b

array([[ 2,  1],
       [14,  9]])

In [13]:
a.dot(b)

array([[ 2,  1],
       [14,  9]])

In [14]:
np.dot(a,b)

array([[ 2,  1],
       [14,  9]])

In [15]:
# +=、-=、*=、/=诸如这些符号表示在左边操作对象上就地修改,但还不支持@=这种操作，可以使用a = a @ b
a+=b

In [16]:
a

array([[4, 4],
       [4, 4]])

In [17]:
b

array([[4, 3],
       [2, 1]])

In [18]:
a*=b

In [19]:
a

array([[16, 12],
       [ 8,  4]])

In [20]:
a/=b

TypeError: No loop matching the specified signature and casting
was found for ufunc true_divide

## 关于轴的问题

In [33]:
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [34]:
a.sum(axis=1)

array([1, 5, 9])

In [35]:
a.sum(axis=0)

array([6, 9])

In [ ]:
a = np.arange(24).reshape(2,3,4)
a

In [ ]:
a.sum(axis=0)

In [ ]:
a.sum(axis=1)

In [ ]:
a.sum(axis=2)

## 创建数组

### 从列表和元组中创建

### 使用numpy内置函数

In [ ]:
# np.ones(shape)   np.ones_like(a)
# np.zeros(shape)    np.zeros_like(a)
# np.full(shape, val)    np.full_like(shape, val)
# np.eye(n)  单位矩阵
# np.empty(shape) 未被初始化
# np.arange(start, end, step)
# np.linspace(start, end, n_points)

In [ ]:
# linspace 指定起始点和元素个数
np.linspace(0,10,4)

In [ ]:
# 默认包括终点，设置endpoint=False可以不包括终点
np.linspace(0,10,4, endpoint=False)

In [ ]:
# 默认创建50个点
a = np.linspace(0,10)
print(a.size)
a

In [ ]:
a = np.array([4,5,3,2], dtype=np.float)
a.dtype

In [ ]:
np.float32([4,3,2])  # 但是np.float不行

### 从文本文件中读取

In [ ]:
a =  np.eye(5)
np.savetxt('eye.txt', a)

## 拼接和分割

In [ ]:
# concatenate
a = np.arange(5)
b = np.zeros(5)
# np.concatenate(a,b) # 错
np.concatenate((a,b))

### 拼接

### 分割

In [ ]:
a = np.arange(9).reshape(3,3)
a

平均分割，有一个标量数字表示

In [ ]:
np.hsplit(a,3)

指定分割，用元组(a,b)表示在序号为a、b上分别切一刀

In [ ]:
a = np.arange(15).reshape(3,5)
a

In [ ]:
np.hsplit(a, (1,3))

## 改变数组形状


In [ ]:
a = np.ones((2,3,4))
a

In [ ]:
# ndarray.reshape不改变原数组
a.reshape(4,6)

In [ ]:
a

In [ ]:
# ndarray.resize改变原来数组
a.resize(4,6)   # 就地修改，没有返回值

In [ ]:
a

In [ ]:
a = np.arange(24).reshape(2,3,4)
b = a.flatten()  
b

In [ ]:
a[0,0] = 100
a

In [ ]:
b

In [ ]:
# np.ravel(a)
a = np.arange(24).reshape(2,3,4)
b = np.ravel(a)
b

In [ ]:
a[0,0] = 100
a

In [ ]:
b

In [ ]:
# 转置
a = np.arange(8).reshape(2,4)
a

In [ ]:
a.T

In [ ]:
a.transpose(1,0)

In [ ]:
# 翻转
a = np.arange(15).reshape(5,3)
a

In [ ]:
a[::-1,:]

## 数据类型

### 数据类型转换

In [ ]:
# ndarray.astype方法一定会创建一个新的数组，即使两个数组类型一样
a = np.arange(24)
b = a.astype(np.float)
a

In [ ]:
b

In [ ]:
# 还可以直接使用Numy内置的类型名称进行类型转换
a = np.arange(10)
b = np.float32(a)
a

In [ ]:
b

In [ ]:
# ! 注意np.float表示python内置浮点类型，不能用于numpy数组类型的转换，可以使用np.float32或者np.float64
b = np.float(a)   

In [ ]:
a = np.full((4,3), 1.0)
a

In [ ]:
b = np.int8(a)
b

### 创建自定义数据类型

In [ ]:
t = np.dtype([('name', np.str_, 40), ('num_items', np.int), ('price', np.float)])
t

## 索引、切片和遍历

In [ ]:
b = np.arange(6).reshape(3,2)
for i in b:    # 对于二维数组，相当与遍历行
    print(i)

In [ ]:
for i in b.flat:
    print(i)

###  索引运算

In [ ]:
a = np.arange(15).reshape(3,5)
a

In [ ]:
a[2,3]

In [ ]:
a[1:, 3]

In [ ]:
a[0:3:2, 0:5:2]

In [ ]:
a[[0,2],[3,4]]

# 通用函数

In [ ]:
a = np.arange(8)
a

In [ ]:
np.diff(a)

In [ ]:
a = np.random.randint(0,100,(3,4))
a

In [ ]:
np.diff(a)

In [ ]:
# np.maximum和np.max的区别
# 前者是基于元素较两个数组，返回一个数组
# 后者是全局比较

# 布尔运算

## 等于

In [ ]:
a = np.arange(5)
b = (a==2)
c = a[b]
a

In [ ]:
b

In [ ]:
c

In [ ]:
a = np.array([[2,4,5,4],[9,4,1,4]])
b = (a==4)
c = a[b]
a

In [ ]:
b

In [ ]:
c

In [ ]:
# where函数
a = np.arange(5)
b = np.array([4,3,2,4,9])
cond = np.array([True,False,False,True,True])
print(a)
print(b)
# True取ａ，False取ｂ
np.where(cond,a,b)

## 与或非 & | 

# 拷贝问题

In [ ]:
a = np.arange(6).reshape(2,3)
b = a
c = a.view()
d = a.copy()
a

In [ ]:
id(a)

In [ ]:
id(b)

In [ ]:
id(c)

In [ ]:
id(d)

In [ ]:
a[0] = 9999
a

In [ ]:
b

In [ ]:
c

In [ ]:
d

In [ ]:
a.resize(3,2)
a

In [ ]:
# b和a完全相同
b

In [ ]:
# c和a指向相同的实际数据部分
# 实际数据部分相同表示数据部分在内存中的存储形式是一样的
# 但是数据在numpy数组中的表现形式是不一样的
# 也就说一个内存形式的数据可以映射为不同的numpy数组表现形式，与之对应的操作也相应发生变化
c

In [ ]:
d

# 随机函数

# 排序

In [32]:
a = np.random.randint(0,100,(3,4))
print(a)
print(np.sort(a))

[[46 84 22 73]
 [ 7 32  4 13]
 [14 63 36 40]]
[[22 46 73 84]
 [ 4  7 13 32]
 [14 36 40 63]]


# Broadcasting

# 矩阵乘法