In [1]:
import numpy as np
print(np.__version__)

1.18.1


# 排序

In [2]:
# np.sort 默认按照最高轴对数组a进行进行从小到大的排序
a = np.random.randint(0,100,(3,4))
print(a)
print(np.sort(a))
sorted = np.sort(a)

[[ 2 26 87 48]
 [13 43 24 82]
 [76  3 13 24]]
[[ 2 26 48 87]
 [13 24 43 82]
 [ 3 13 24 76]]


In [3]:
# np.argsort 默认按照最高轴对数组a进行从小到大排序，但是返回的不是原来的数值，而是其在原数组的索引
argsorted = np.argsort(a)
np.argsort(a)

array([[0, 1, 3, 2],
       [0, 2, 1, 3],
       [1, 2, 3, 0]])

In [6]:
a = np.arange(12)
np.random.shuffle(a)
a

array([ 1,  6,  4, 11, 10,  5,  9,  8,  3,  0,  2,  7])

In [7]:
np.sort(a)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
np.argsort(a)

array([ 9,  0, 10,  8,  2,  5,  1, 11,  7,  6,  4,  3])

In [9]:
a[np.argsort(a)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])