In [1]:
import numpy as np
from scipy.linalg import solve

In [2]:
a = np.array([[0.8788,0.7468,0.6839,0.675,0.6633,0.5725,0.5213],
[0.8594,0.7551,0.7267,0.7464,0.606,0.5078,0.5217],
[0.8125,0.8025,0.6801,0.6128,0.6378,0.5352,0.406],
[0.8316,0.7648,0.7257,0.7422,0.6206,0.5548,0.5299],
[0.9074,0.6157,0.5417,0.5278,0.4393,0.6093,0.463],
[0.8759,0.8101,0.7981,0.7076,0.6444,0.591,0.4994],
[0.9165,0.8378,0.6849,0.5702,0.6313,0.5765,0.4482]])

In [3]:
b = np.array([77.33,78.13,75.89,77.38,69.43,81.81,80.55])

In [4]:
x1 = solve(a,b)
print(x1)

[37.17304681 29.51116839 22.25824131  7.49620674  3.73704081 -0.03946393
 -0.22089191]


In [5]:
a2 = a[:,:5][:5]
a2

array([[0.8788, 0.7468, 0.6839, 0.675 , 0.6633],
       [0.8594, 0.7551, 0.7267, 0.7464, 0.606 ],
       [0.8125, 0.8025, 0.6801, 0.6128, 0.6378],
       [0.8316, 0.7648, 0.7257, 0.7422, 0.6206],
       [0.9074, 0.6157, 0.5417, 0.5278, 0.4393]])

In [6]:
b2 = b[:5]
b2

array([77.33, 78.13, 75.89, 77.38, 69.43])

In [7]:
x2 = solve(a2,b2)

In [8]:
print(x2)

[37.10063439 28.7916561  24.08645712  6.42297592  3.6425704 ]


In [9]:
10/27

0.37037037037037035

In [10]:
coef = np.array([10/27, 8/27, 6/27, 2/27, 1/27, 0, 0])*100

In [11]:
coef

array([37.03703704, 29.62962963, 22.22222222,  7.40740741,  3.7037037 ,
        0.        ,  0.        ])

In [12]:
a.dot(coef)

array([77.33      , 78.12518519, 75.88518519, 77.3837037 , 69.42481481,
       81.80740741, 80.55      ])

In [13]:
a = np.array([4,5,3,2])

In [14]:
a

array([4, 5, 3, 2])

In [16]:
a[[3,2,1,0]]

array([2, 3, 5, 4])